version: '3.8'
services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Optional: persist data across restarts
      - ./init-db:/docker-entrypoint-initdb.d  # Mount the init-db directory
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  init-db:
    build:
      context: .
      dockerfile: Dockerfile  # Create a Dockerfile that uses the init.sh script
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d  # Place your SQL files here
volumes:
  postgres_data: