# Use the official Node.js image.
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build TypeScript files
RUN npm run build

# Expose the application port
EXPOSE 4000

# Start the application from the dist
CMD ["node", "dist/server.js"]